BakkerTom/happy-news

CONTRIBUTING.md

I will repair the damaged file later :)

pull request test

---

CONTRIBUTING.md

Reverts BakkerTom/happy-news#3

Revert "pull request test"

---

.github/PULL_REQUEST_TEMPLATE.md

I have created the PULL_REQUEST_TEMPLATE. This file defines our 'Definition of done' and helps as a guide for new Pull Requests.

Created PULL_REQUEST_TEMPLATE

---

shared/build.gradle
shared/src/main/java/Post.java

added the post class and hibernate gradle dependency

---

crawler/build.gradle
crawler/src/main/java/nl/fhict/happynews/crawler/Application.java
crawler/src/main/java/nl/fhict/happynews/crawler/CrawlerController.java
crawler/src/main/java/nl/fhict/happynews/crawler/NewsRetriever.java
crawler/src/main/java/nl/fhict/happynews/crawler/models/newsapi/Article.java
crawler/src/main/java/nl/fhict/happynews/crawler/models/newsapi/NewsSource.java
crawler/src/main/java/nl/fhict/happynews/crawler/repository/PostRepository.java
crawler/src/main/resources/application.yml
crawler/src/test/java/nl/fhict/happynews/crawler/CrawlerControllerTest.java
shared/build.gradle
shared/src/main/java/nl/fhict/happynews/shared/Post.java

Hn 17 setup microservice

---

android/build.gradle
android/src/main/AndroidManifest.xml
android/src/main/java/nl/fhict/happynews/android/Activitys/MainActivity.java
android/src/main/java/nl/fhict/happynews/android/Adapters/PostAdapter.java
android/src/main/java/nl/fhict/happynews/android/Models/Post.java
android/src/main/java/nl/fhict/happynews/android/PostManager.java
android/src/main/res/layout/activity_main.xml
android/src/main/res/layout/list_item_post.xml
android/src/main/res/layout/list_item_post_2.xml
gradle.properties
shared/src/main/java/nl/fhict/happynews/shared/Post.java

Setup for the android application with a listview with multiple xml files per list item

Hm setup android application

---

crawler/src/main/java/nl/fhict/happynews/crawler/CrawlerController.java

removed stacktrace and changed error messaging

---

api/src/main/java/nl/fhict/happynews/api/controller/PostController.java
api/src/main/java/nl/fhict/happynews/api/hibernate/PostRepository.java
api/src/test/java/nl/fhict/happynews/api/controller/PostControllerTest.java

hn-34-add-option-to-retrieve-ordered-by-last

---

api/build.gradle
crawler/build.gradle
web/build.gradle

Expose commit info in `/info` admin endpoint.
https://happynews-admin.svendubbeld.nl/info
https://happynews-api-admin.svendubbeld.nl/info
https://happynews-crawler-admin.svendubbeld.nl/info

Show commit info in status

---

android/src/main/java/nl/fhict/happynews/android/Activitys/MainActivity.java
android/src/main/java/nl/fhict/happynews/android/Adapters/PostAdapter.java
android/src/main/java/nl/fhict/happynews/android/Models/Post.java
android/src/main/java/nl/fhict/happynews/android/PostManager.java
android/src/test/java/nl/fhict/happynews/android/Adapters/PostAdapterTest.java

7 fix null exception

---

android/src/main/java/nl/fhict/happynews/android/Adapters/PostAdapter.java

69 android fix layoutinflation

---

README.md

Added CODEBEAT badge to readme

---

android/src/main/java/nl/fhict/happynews/android/PostManager.java

HOTFIX: Revert debug URL

---

crawler/src/main/java/nl/fhict/happynews/crawler/analyzer/PositivityAnalyzer.java

refactored to inputstream

---

android/src/main/java/nl/fhict/happynews/android/activity/MainActivity.java
android/src/main/res/layout/list_item_post.xml

Fixed bug
https://fhictwo.atlassian.net/browse/HN-51

Fixed Z translation bug

---

crawler/src/main/java/nl/fhict/happynews/crawler/analyzer/PositivityAnalyzer.java
crawler/src/main/java/nl/fhict/happynews/crawler/crawler/NewsCrawler.java
crawler/src/test/java/nl/fhict/happynews/crawler/PositivityAnalyzerTest.java

Added lower case support and removed espn

Hn hotfix lower case

---

crawler/src/main/java/nl/fhict/happynews/crawler/crawler/TwitterCrawler.java

I have monitored the amount of tweets in the app the past few days and I noticed that the tweets are a bit overrepresented. Changing the max amount of tweets per hour from 5 to 3 should balance this.

Tweets-balance-patch

---

api/src/test/java/nl/fhict/happynews/api/controller/PostControllerTest.java
crawler/src/main/java/nl/fhict/happynews/crawler/crawler/QuoteCrawler.java

Bugfix QuoteCrawler

---

build.gradle
crawler/build.gradle
crawler/src/main/java/nl/fhict/happynews/crawler/AppConfig.java
crawler/src/main/java/nl/fhict/happynews/crawler/extractor/ArticleExtractor.java
crawler/src/main/resources/application.yml

Specify a connection timeout to resolve bug [HN-57](https://fhictwo.atlassian.net/browse/HN-57).
---

Specify connection timeout for extractor

---

README.md

Added google play icon and updated json example to README.md

---

crawler/src/main/resources/hashtags.csv

removed #happy to prevent more XXX content from getting through
Can be restored when a blacklist of bad words is implemented.

Remove #happy from hastags (temporary)

---

.gitignore
README.md
api/build.gradle
api/src/main/java/nl/fhict/happynews/api/SwaggerConfig.java
api/src/main/java/nl/fhict/happynews/api/controller/PostController.java
api/src/main/java/nl/fhict/happynews/api/controller/admin/AdminPostController.java
api/src/main/java/nl/fhict/happynews/api/controller/admin/UserController.java
api/src/main/java/nl/fhict/happynews/api/exception/PostCreationException.java
api/src/main/java/nl/fhict/happynews/api/hibernate/PostRepository.java
api/src/main/java/nl/fhict/happynews/api/util/HideRequest.java
api/src/main/java/nl/fhict/happynews/api/validator/PostValidator.java
api/src/main/java/nl/fhict/happynews/api/validator/UserValidator.java
api/src/test/java/nl/fhict/happynews/api/controller/AdminPostControllerTest.java
api/src/test/java/nl/fhict/happynews/api/controller/PostControllerTest.java
build.gradle
crawler/build.gradle
crawler/src/main/java/nl/fhict/happynews/crawler/crawler/NewsCrawler.java
crawler/src/main/java/nl/fhict/happynews/crawler/crawler/QuoteCrawler.java
crawler/src/main/java/nl/fhict/happynews/crawler/crawler/TwitterCrawler.java
crawler/src/main/java/nl/fhict/happynews/crawler/model/newsapi/Article.java
shared/build.gradle
shared/src/main/java/nl/fhict/happynews/shared/Post.java

Posts can be hidden from the admin API. Hidden posts will be excluded when requesting posts from the public API.
---

Add API endpoints for manipulating posts as admin

---

api/src/main/java/nl/fhict/happynews/api/Setup.java
api/src/main/java/nl/fhict/happynews/api/WebSecurityConfig.java
api/src/main/java/nl/fhict/happynews/api/auth/PasswordChangeRequest.java
api/src/main/java/nl/fhict/happynews/api/auth/User.java
api/src/main/java/nl/fhict/happynews/api/controller/admin/UserController.java
api/src/main/java/nl/fhict/happynews/api/validator/PasswordValidator.java
api/src/main/java/nl/fhict/happynews/api/validator/UserValidator.java
api/src/test/java/nl/fhict/happynews/api/auth/oauth2/OAuth2Test.java
api/src/test/java/nl/fhict/happynews/api/controller/UserControllerTest.java

This PR fixes some security issues.
* Encode passwords before saving to database
* Allow user to change their own password
* Create a default user if the application has no users
---

Patch security issues

---

api/src/main/java/nl/fhict/happynews/api/WebMvcConfig.java

@BakkerTom I enabled CORS for all origins. Is this ok or do you prefer it for specific origins?
---

Enable CORS

---

api/src/main/java/nl/fhict/happynews/api/ResourceServerConfig.java

Allow preflight checks, for CORS of course.
---

Allow preflight checks

---

api/src/main/java/nl/fhict/happynews/api/AuthorizationServerConfig.java
api/src/main/java/nl/fhict/happynews/api/WebSecurityConfig.java

Added configuration to WebSecurityConfig

---

api/src/main/java/nl/fhict/happynews/api/WebMvcConfig.java

Re-add swagger UI

---

android/build.gradle
api/build.gradle
crawler/build.gradle

Bumped version numbers to 1.1

---

web/src/main/client/src/App.js
web/src/main/client/src/Authenticator.js
web/src/main/client/src/components/login/Login.css
web/src/main/client/src/components/login/Login.js
web/src/main/client/src/index.css

This PR consists mainly of the creation of a login screen.
- Token request is moved from App.js to new Login component
- When user is authenticated the parent will be signaled and the Login component is swapped out with the Feed component
---

HN-59 Login screen

---

android/src/main/res/values/styles.xml
crawler/src/main/resources/positivewords.txt

Removed trump from positive words
Fixed fab problem

Hn issue fixing
